### ISSUE TITLE
Fix your package.json

### ISSUE THREAD

**Issue by rom1504** [lastuniverse/minecraft.proxy.bot.gui#1]
https://github.com/lastuniverse/minecraft.proxy.bot.gui/blob/master/package.json#L12 : you can depend on the last minecraft protocol (0.19.3) so `npm install` can just work.

https://github.com/lastuniverse/minecraft.proxy.bot.gui/blob/master/package.json#L13 you should set a specific version (can start with ^ to make it more flexible)

Also you don't need to include rbot directly there https://github.com/lastuniverse/minecraft.proxy.bot.gui/tree/master/bot/rbot

you can use the one from node_modules

**Comment by lastuniverse** [comment]
ok.
how will the time and effort, I will make corrections.

**Comment by lastuniverse** [comment]
ready
